// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module nodalSolver_vetmat (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        G_vec_I_1_i,
        G_vec_I_1_o,
        G_vec_I_1_o_ap_vld,
        G_vec_I_2_i,
        G_vec_I_2_o,
        G_vec_I_2_o_ap_vld,
        G_vec_I_3_i,
        G_vec_I_3_o,
        G_vec_I_3_o_ap_vld,
        G_vec_V_0,
        G_vec_V_0_ap_vld,
        G_vec_V_1,
        G_vec_V_1_ap_vld,
        G_vec_V_2,
        G_vec_V_2_ap_vld,
        grp_fu_165_p_din0,
        grp_fu_165_p_din1,
        grp_fu_165_p_opcode,
        grp_fu_165_p_dout0,
        grp_fu_165_p_ce,
        grp_fu_170_p_din0,
        grp_fu_170_p_din1,
        grp_fu_170_p_opcode,
        grp_fu_170_p_dout0,
        grp_fu_170_p_ce,
        grp_fu_175_p_din0,
        grp_fu_175_p_din1,
        grp_fu_175_p_opcode,
        grp_fu_175_p_dout0,
        grp_fu_175_p_ce,
        grp_fu_720_p_din0,
        grp_fu_720_p_din1,
        grp_fu_720_p_opcode,
        grp_fu_720_p_dout0,
        grp_fu_720_p_ce,
        grp_fu_724_p_din0,
        grp_fu_724_p_din1,
        grp_fu_724_p_opcode,
        grp_fu_724_p_dout0,
        grp_fu_724_p_ce,
        grp_fu_728_p_din0,
        grp_fu_728_p_din1,
        grp_fu_728_p_opcode,
        grp_fu_728_p_dout0,
        grp_fu_728_p_ce,
        grp_fu_732_p_din0,
        grp_fu_732_p_din1,
        grp_fu_732_p_opcode,
        grp_fu_732_p_dout0,
        grp_fu_732_p_ce,
        grp_fu_736_p_din0,
        grp_fu_736_p_din1,
        grp_fu_736_p_opcode,
        grp_fu_736_p_dout0,
        grp_fu_736_p_ce,
        grp_fu_740_p_din0,
        grp_fu_740_p_din1,
        grp_fu_740_p_opcode,
        grp_fu_740_p_dout0,
        grp_fu_740_p_ce,
        grp_fu_180_p_din0,
        grp_fu_180_p_din1,
        grp_fu_180_p_dout0,
        grp_fu_180_p_ce,
        grp_fu_185_p_din0,
        grp_fu_185_p_din1,
        grp_fu_185_p_dout0,
        grp_fu_185_p_ce,
        grp_fu_190_p_din0,
        grp_fu_190_p_din1,
        grp_fu_190_p_dout0,
        grp_fu_190_p_ce,
        grp_fu_744_p_din0,
        grp_fu_744_p_din1,
        grp_fu_744_p_dout0,
        grp_fu_744_p_ce,
        grp_fu_748_p_din0,
        grp_fu_748_p_din1,
        grp_fu_748_p_dout0,
        grp_fu_748_p_ce,
        grp_fu_752_p_din0,
        grp_fu_752_p_din1,
        grp_fu_752_p_dout0,
        grp_fu_752_p_ce,
        grp_fu_756_p_din0,
        grp_fu_756_p_din1,
        grp_fu_756_p_dout0,
        grp_fu_756_p_ce,
        grp_fu_760_p_din0,
        grp_fu_760_p_din1,
        grp_fu_760_p_dout0,
        grp_fu_760_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] G_vec_I_1_i;
output  [31:0] G_vec_I_1_o;
output   G_vec_I_1_o_ap_vld;
input  [31:0] G_vec_I_2_i;
output  [31:0] G_vec_I_2_o;
output   G_vec_I_2_o_ap_vld;
input  [31:0] G_vec_I_3_i;
output  [31:0] G_vec_I_3_o;
output   G_vec_I_3_o_ap_vld;
output  [31:0] G_vec_V_0;
output   G_vec_V_0_ap_vld;
output  [31:0] G_vec_V_1;
output   G_vec_V_1_ap_vld;
output  [31:0] G_vec_V_2;
output   G_vec_V_2_ap_vld;
output  [31:0] grp_fu_165_p_din0;
output  [31:0] grp_fu_165_p_din1;
output  [1:0] grp_fu_165_p_opcode;
input  [31:0] grp_fu_165_p_dout0;
output   grp_fu_165_p_ce;
output  [31:0] grp_fu_170_p_din0;
output  [31:0] grp_fu_170_p_din1;
output  [1:0] grp_fu_170_p_opcode;
input  [31:0] grp_fu_170_p_dout0;
output   grp_fu_170_p_ce;
output  [31:0] grp_fu_175_p_din0;
output  [31:0] grp_fu_175_p_din1;
output  [1:0] grp_fu_175_p_opcode;
input  [31:0] grp_fu_175_p_dout0;
output   grp_fu_175_p_ce;
output  [31:0] grp_fu_720_p_din0;
output  [31:0] grp_fu_720_p_din1;
output  [1:0] grp_fu_720_p_opcode;
input  [31:0] grp_fu_720_p_dout0;
output   grp_fu_720_p_ce;
output  [31:0] grp_fu_724_p_din0;
output  [31:0] grp_fu_724_p_din1;
output  [1:0] grp_fu_724_p_opcode;
input  [31:0] grp_fu_724_p_dout0;
output   grp_fu_724_p_ce;
output  [31:0] grp_fu_728_p_din0;
output  [31:0] grp_fu_728_p_din1;
output  [1:0] grp_fu_728_p_opcode;
input  [31:0] grp_fu_728_p_dout0;
output   grp_fu_728_p_ce;
output  [31:0] grp_fu_732_p_din0;
output  [31:0] grp_fu_732_p_din1;
output  [1:0] grp_fu_732_p_opcode;
input  [31:0] grp_fu_732_p_dout0;
output   grp_fu_732_p_ce;
output  [31:0] grp_fu_736_p_din0;
output  [31:0] grp_fu_736_p_din1;
output  [1:0] grp_fu_736_p_opcode;
input  [31:0] grp_fu_736_p_dout0;
output   grp_fu_736_p_ce;
output  [31:0] grp_fu_740_p_din0;
output  [31:0] grp_fu_740_p_din1;
output  [1:0] grp_fu_740_p_opcode;
input  [31:0] grp_fu_740_p_dout0;
output   grp_fu_740_p_ce;
output  [31:0] grp_fu_180_p_din0;
output  [31:0] grp_fu_180_p_din1;
input  [31:0] grp_fu_180_p_dout0;
output   grp_fu_180_p_ce;
output  [31:0] grp_fu_185_p_din0;
output  [31:0] grp_fu_185_p_din1;
input  [31:0] grp_fu_185_p_dout0;
output   grp_fu_185_p_ce;
output  [31:0] grp_fu_190_p_din0;
output  [31:0] grp_fu_190_p_din1;
input  [31:0] grp_fu_190_p_dout0;
output   grp_fu_190_p_ce;
output  [31:0] grp_fu_744_p_din0;
output  [31:0] grp_fu_744_p_din1;
input  [31:0] grp_fu_744_p_dout0;
output   grp_fu_744_p_ce;
output  [31:0] grp_fu_748_p_din0;
output  [31:0] grp_fu_748_p_din1;
input  [31:0] grp_fu_748_p_dout0;
output   grp_fu_748_p_ce;
output  [31:0] grp_fu_752_p_din0;
output  [31:0] grp_fu_752_p_din1;
input  [31:0] grp_fu_752_p_dout0;
output   grp_fu_752_p_ce;
output  [31:0] grp_fu_756_p_din0;
output  [31:0] grp_fu_756_p_din1;
input  [31:0] grp_fu_756_p_dout0;
output   grp_fu_756_p_ce;
output  [31:0] grp_fu_760_p_din0;
output  [31:0] grp_fu_760_p_din1;
input  [31:0] grp_fu_760_p_dout0;
output   grp_fu_760_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] G_vec_I_1_o;
reg G_vec_I_1_o_ap_vld;
reg[31:0] G_vec_I_2_o;
reg G_vec_I_2_o_ap_vld;
reg[31:0] G_vec_I_3_o;
reg G_vec_I_3_o_ap_vld;
reg G_vec_V_0_ap_vld;
reg G_vec_V_1_ap_vld;
reg G_vec_V_2_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] grp_fu_71_p2;
reg   [31:0] mul_0_1_reg_174;
wire   [31:0] grp_fu_76_p2;
reg   [31:0] mul_1_1_reg_179;
wire   [31:0] grp_fu_81_p2;
reg   [31:0] mul_2_1_reg_184;
wire   [31:0] grp_fu_32_p2;
reg   [31:0] acc_1_0_1_reg_196;
wire   [31:0] grp_fu_86_p2;
reg   [31:0] mul_0_2_reg_201;
wire   [31:0] grp_fu_37_p2;
reg   [31:0] acc_1_1_1_reg_206;
wire   [31:0] grp_fu_91_p2;
reg   [31:0] mul_1_2_reg_211;
wire   [31:0] grp_fu_42_p2;
reg   [31:0] acc_1_2_1_reg_216;
wire   [31:0] grp_fu_96_p2;
reg   [31:0] mul_2_2_reg_221;
reg   [31:0] G_vec_I_3_load_reg_226;
reg   [31:0] G_vec_I_3_load_reg_226_pp0_iter9_reg;
reg   [31:0] G_vec_I_3_load_reg_226_pp0_iter10_reg;
wire   [31:0] grp_fu_47_p2;
reg   [31:0] acc_1_0_2_reg_233;
wire   [31:0] grp_fu_51_p2;
reg   [31:0] acc_1_1_2_reg_238;
wire   [31:0] grp_fu_101_p2;
reg   [31:0] mul_1_3_reg_243;
wire   [31:0] grp_fu_55_p2;
reg   [31:0] acc_1_2_2_reg_248;
wire   [31:0] grp_fu_106_p2;
reg   [31:0] mul_2_3_reg_253;
wire    ap_block_pp0_stage0_subdone;
wire   [31:0] grp_fu_59_p2;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] grp_fu_63_p2;
wire   [31:0] grp_fu_67_p2;
wire   [31:0] grp_fu_32_p0;
wire   [31:0] grp_fu_32_p1;
wire   [31:0] grp_fu_37_p0;
wire   [31:0] grp_fu_37_p1;
wire   [31:0] grp_fu_42_p0;
wire   [31:0] grp_fu_42_p1;
wire   [31:0] grp_fu_47_p0;
wire   [31:0] grp_fu_47_p1;
wire   [31:0] grp_fu_51_p0;
wire   [31:0] grp_fu_51_p1;
wire   [31:0] grp_fu_55_p0;
wire   [31:0] grp_fu_55_p1;
wire   [31:0] grp_fu_59_p0;
wire   [31:0] grp_fu_59_p1;
wire   [31:0] grp_fu_63_p0;
wire   [31:0] grp_fu_63_p1;
wire   [31:0] grp_fu_67_p0;
wire   [31:0] grp_fu_67_p1;
wire   [31:0] grp_fu_71_p0;
wire   [31:0] grp_fu_71_p1;
wire   [31:0] grp_fu_76_p0;
wire   [31:0] grp_fu_76_p1;
wire   [31:0] grp_fu_81_p0;
wire   [31:0] grp_fu_81_p1;
wire   [31:0] grp_fu_86_p0;
wire   [31:0] grp_fu_86_p1;
wire   [31:0] grp_fu_91_p0;
wire   [31:0] grp_fu_91_p1;
wire   [31:0] grp_fu_96_p0;
wire   [31:0] grp_fu_96_p1;
wire   [31:0] grp_fu_101_p0;
wire   [31:0] grp_fu_101_p1;
wire   [31:0] grp_fu_106_p0;
wire   [31:0] grp_fu_106_p1;
wire    grp_fu_32_ce;
wire    grp_fu_37_ce;
wire    grp_fu_42_ce;
wire    grp_fu_47_ce;
wire    grp_fu_51_ce;
wire    grp_fu_55_ce;
wire    grp_fu_59_ce;
wire    grp_fu_63_ce;
wire    grp_fu_67_ce;
wire    grp_fu_71_ce;
wire    grp_fu_76_ce;
wire    grp_fu_81_ce;
wire    grp_fu_86_ce;
wire    grp_fu_91_ce;
wire    grp_fu_96_ce;
wire    grp_fu_101_ce;
wire    grp_fu_106_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to13;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_block_pp0_stage0_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        G_vec_I_3_load_reg_226 <= G_vec_I_3_i;
        G_vec_I_3_load_reg_226_pp0_iter10_reg <= G_vec_I_3_load_reg_226_pp0_iter9_reg;
        G_vec_I_3_load_reg_226_pp0_iter9_reg <= G_vec_I_3_load_reg_226;
        acc_1_0_1_reg_196 <= grp_fu_165_p_dout0;
        acc_1_0_2_reg_233 <= grp_fu_720_p_dout0;
        acc_1_1_1_reg_206 <= grp_fu_170_p_dout0;
        acc_1_1_2_reg_238 <= grp_fu_724_p_dout0;
        acc_1_2_1_reg_216 <= grp_fu_175_p_dout0;
        acc_1_2_2_reg_248 <= grp_fu_728_p_dout0;
        mul_0_1_reg_174 <= grp_fu_180_p_dout0;
        mul_0_2_reg_201 <= grp_fu_744_p_dout0;
        mul_1_1_reg_179 <= grp_fu_185_p_dout0;
        mul_1_2_reg_211 <= grp_fu_748_p_dout0;
        mul_1_3_reg_243 <= grp_fu_756_p_dout0;
        mul_2_1_reg_184 <= grp_fu_190_p_dout0;
        mul_2_2_reg_221 <= grp_fu_752_p_dout0;
        mul_2_3_reg_253 <= grp_fu_760_p_dout0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        G_vec_I_1_o = 32'd0;
    end else begin
        G_vec_I_1_o = G_vec_I_1_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        G_vec_I_1_o_ap_vld = 1'b1;
    end else begin
        G_vec_I_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        G_vec_I_2_o = 32'd0;
    end else begin
        G_vec_I_2_o = G_vec_I_2_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        G_vec_I_2_o_ap_vld = 1'b1;
    end else begin
        G_vec_I_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        G_vec_I_3_o = 32'd0;
    end else begin
        G_vec_I_3_o = G_vec_I_3_i;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        G_vec_I_3_o_ap_vld = 1'b1;
    end else begin
        G_vec_I_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        G_vec_V_0_ap_vld = 1'b1;
    end else begin
        G_vec_V_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        G_vec_V_1_ap_vld = 1'b1;
    end else begin
        G_vec_V_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        G_vec_V_2_ap_vld = 1'b1;
    end else begin
        G_vec_V_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to13 = 1'b1;
    end else begin
        ap_idle_pp0_0to13 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to13 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign G_vec_V_0 = grp_fu_732_p_dout0;

assign G_vec_V_1 = grp_fu_736_p_dout0;

assign G_vec_V_2 = grp_fu_740_p_dout0;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign grp_fu_101_ce = 1'b1;

assign grp_fu_101_p0 = G_vec_I_3_i;

assign grp_fu_101_p1 = 32'd1065190042;

assign grp_fu_101_p2 = grp_fu_756_p_dout0;

assign grp_fu_106_ce = 1'b1;

assign grp_fu_106_p0 = G_vec_I_3_i;

assign grp_fu_106_p1 = 32'd1064893363;

assign grp_fu_106_p2 = grp_fu_760_p_dout0;

assign grp_fu_165_p_ce = 1'b1;

assign grp_fu_165_p_din0 = mul_0_1_reg_174;

assign grp_fu_165_p_din1 = 32'd0;

assign grp_fu_165_p_opcode = 2'd0;

assign grp_fu_170_p_ce = 1'b1;

assign grp_fu_170_p_din0 = mul_1_1_reg_179;

assign grp_fu_170_p_din1 = 32'd0;

assign grp_fu_170_p_opcode = 2'd0;

assign grp_fu_175_p_ce = 1'b1;

assign grp_fu_175_p_din0 = mul_2_1_reg_184;

assign grp_fu_175_p_din1 = 32'd0;

assign grp_fu_175_p_opcode = 2'd0;

assign grp_fu_180_p_ce = 1'b1;

assign grp_fu_180_p_din0 = G_vec_I_1_i;

assign grp_fu_180_p_din1 = 32'd0;

assign grp_fu_185_p_ce = 1'b1;

assign grp_fu_185_p_din0 = G_vec_I_1_i;

assign grp_fu_185_p_din1 = 32'd1092514208;

assign grp_fu_190_p_ce = 1'b1;

assign grp_fu_190_p_din0 = G_vec_I_1_i;

assign grp_fu_190_p_din1 = 32'd1092328784;

assign grp_fu_32_ce = 1'b1;

assign grp_fu_32_p0 = mul_0_1_reg_174;

assign grp_fu_32_p1 = 32'd0;

assign grp_fu_32_p2 = grp_fu_165_p_dout0;

assign grp_fu_37_ce = 1'b1;

assign grp_fu_37_p0 = mul_1_1_reg_179;

assign grp_fu_37_p1 = 32'd0;

assign grp_fu_37_p2 = grp_fu_170_p_dout0;

assign grp_fu_42_ce = 1'b1;

assign grp_fu_42_p0 = mul_2_1_reg_184;

assign grp_fu_42_p1 = 32'd0;

assign grp_fu_42_p2 = grp_fu_175_p_dout0;

assign grp_fu_47_ce = 1'b1;

assign grp_fu_47_p0 = acc_1_0_1_reg_196;

assign grp_fu_47_p1 = mul_0_2_reg_201;

assign grp_fu_47_p2 = grp_fu_720_p_dout0;

assign grp_fu_51_ce = 1'b1;

assign grp_fu_51_p0 = acc_1_1_1_reg_206;

assign grp_fu_51_p1 = mul_1_2_reg_211;

assign grp_fu_51_p2 = grp_fu_724_p_dout0;

assign grp_fu_55_ce = 1'b1;

assign grp_fu_55_p0 = acc_1_2_1_reg_216;

assign grp_fu_55_p1 = mul_2_2_reg_221;

assign grp_fu_55_p2 = grp_fu_728_p_dout0;

assign grp_fu_59_ce = 1'b1;

assign grp_fu_59_p0 = acc_1_0_2_reg_233;

assign grp_fu_59_p1 = G_vec_I_3_load_reg_226_pp0_iter10_reg;

assign grp_fu_59_p2 = grp_fu_732_p_dout0;

assign grp_fu_63_ce = 1'b1;

assign grp_fu_63_p0 = acc_1_1_2_reg_238;

assign grp_fu_63_p1 = mul_1_3_reg_243;

assign grp_fu_63_p2 = grp_fu_736_p_dout0;

assign grp_fu_67_ce = 1'b1;

assign grp_fu_67_p0 = acc_1_2_2_reg_248;

assign grp_fu_67_p1 = mul_2_3_reg_253;

assign grp_fu_67_p2 = grp_fu_740_p_dout0;

assign grp_fu_71_ce = 1'b1;

assign grp_fu_71_p0 = G_vec_I_1_i;

assign grp_fu_71_p1 = 32'd0;

assign grp_fu_71_p2 = grp_fu_180_p_dout0;

assign grp_fu_720_p_ce = 1'b1;

assign grp_fu_720_p_din0 = acc_1_0_1_reg_196;

assign grp_fu_720_p_din1 = mul_0_2_reg_201;

assign grp_fu_720_p_opcode = 2'd0;

assign grp_fu_724_p_ce = 1'b1;

assign grp_fu_724_p_din0 = acc_1_1_1_reg_206;

assign grp_fu_724_p_din1 = mul_1_2_reg_211;

assign grp_fu_724_p_opcode = 2'd0;

assign grp_fu_728_p_ce = 1'b1;

assign grp_fu_728_p_din0 = acc_1_2_1_reg_216;

assign grp_fu_728_p_din1 = mul_2_2_reg_221;

assign grp_fu_728_p_opcode = 2'd0;

assign grp_fu_732_p_ce = 1'b1;

assign grp_fu_732_p_din0 = acc_1_0_2_reg_233;

assign grp_fu_732_p_din1 = G_vec_I_3_load_reg_226_pp0_iter10_reg;

assign grp_fu_732_p_opcode = 2'd0;

assign grp_fu_736_p_ce = 1'b1;

assign grp_fu_736_p_din0 = acc_1_1_2_reg_238;

assign grp_fu_736_p_din1 = mul_1_3_reg_243;

assign grp_fu_736_p_opcode = 2'd0;

assign grp_fu_740_p_ce = 1'b1;

assign grp_fu_740_p_din0 = acc_1_2_2_reg_248;

assign grp_fu_740_p_din1 = mul_2_3_reg_253;

assign grp_fu_740_p_opcode = 2'd0;

assign grp_fu_744_p_ce = 1'b1;

assign grp_fu_744_p_din0 = G_vec_I_2_i;

assign grp_fu_744_p_din1 = 32'd0;

assign grp_fu_748_p_ce = 1'b1;

assign grp_fu_748_p_din0 = G_vec_I_2_i;

assign grp_fu_748_p_din1 = 32'd1092328784;

assign grp_fu_752_p_ce = 1'b1;

assign grp_fu_752_p_din0 = G_vec_I_2_i;

assign grp_fu_752_p_din1 = 32'd1104889445;

assign grp_fu_756_p_ce = 1'b1;

assign grp_fu_756_p_din0 = G_vec_I_3_i;

assign grp_fu_756_p_din1 = 32'd1065190042;

assign grp_fu_760_p_ce = 1'b1;

assign grp_fu_760_p_din0 = G_vec_I_3_i;

assign grp_fu_760_p_din1 = 32'd1064893363;

assign grp_fu_76_ce = 1'b1;

assign grp_fu_76_p0 = G_vec_I_1_i;

assign grp_fu_76_p1 = 32'd1092514208;

assign grp_fu_76_p2 = grp_fu_185_p_dout0;

assign grp_fu_81_ce = 1'b1;

assign grp_fu_81_p0 = G_vec_I_1_i;

assign grp_fu_81_p1 = 32'd1092328784;

assign grp_fu_81_p2 = grp_fu_190_p_dout0;

assign grp_fu_86_ce = 1'b1;

assign grp_fu_86_p0 = G_vec_I_2_i;

assign grp_fu_86_p1 = 32'd0;

assign grp_fu_86_p2 = grp_fu_744_p_dout0;

assign grp_fu_91_ce = 1'b1;

assign grp_fu_91_p0 = G_vec_I_2_i;

assign grp_fu_91_p1 = 32'd1092328784;

assign grp_fu_91_p2 = grp_fu_748_p_dout0;

assign grp_fu_96_ce = 1'b1;

assign grp_fu_96_p0 = G_vec_I_2_i;

assign grp_fu_96_p1 = 32'd1104889445;

assign grp_fu_96_p2 = grp_fu_752_p_dout0;

endmodule //nodalSolver_vetmat
