// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="nodalSolver_nodalSolver,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.700000,HLS_SYN_LAT=78,HLS_SYN_TPT=none,HLS_SYN_MEM=20,HLS_SYN_DSP=0,HLS_SYN_FF=9667,HLS_SYN_LUT=15551,HLS_VERSION=2020_2}" *)

module nodalSolver (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_return
);

parameter    ap_ST_fsm_state1 = 56'd1;
parameter    ap_ST_fsm_state2 = 56'd2;
parameter    ap_ST_fsm_state3 = 56'd4;
parameter    ap_ST_fsm_state4 = 56'd8;
parameter    ap_ST_fsm_state5 = 56'd16;
parameter    ap_ST_fsm_state6 = 56'd32;
parameter    ap_ST_fsm_state7 = 56'd64;
parameter    ap_ST_fsm_state8 = 56'd128;
parameter    ap_ST_fsm_state9 = 56'd256;
parameter    ap_ST_fsm_state10 = 56'd512;
parameter    ap_ST_fsm_state11 = 56'd1024;
parameter    ap_ST_fsm_state12 = 56'd2048;
parameter    ap_ST_fsm_state13 = 56'd4096;
parameter    ap_ST_fsm_state14 = 56'd8192;
parameter    ap_ST_fsm_state15 = 56'd16384;
parameter    ap_ST_fsm_state16 = 56'd32768;
parameter    ap_ST_fsm_state17 = 56'd65536;
parameter    ap_ST_fsm_state18 = 56'd131072;
parameter    ap_ST_fsm_state19 = 56'd262144;
parameter    ap_ST_fsm_state20 = 56'd524288;
parameter    ap_ST_fsm_state21 = 56'd1048576;
parameter    ap_ST_fsm_state22 = 56'd2097152;
parameter    ap_ST_fsm_state23 = 56'd4194304;
parameter    ap_ST_fsm_state24 = 56'd8388608;
parameter    ap_ST_fsm_state25 = 56'd16777216;
parameter    ap_ST_fsm_state26 = 56'd33554432;
parameter    ap_ST_fsm_state27 = 56'd67108864;
parameter    ap_ST_fsm_state28 = 56'd134217728;
parameter    ap_ST_fsm_state29 = 56'd268435456;
parameter    ap_ST_fsm_state30 = 56'd536870912;
parameter    ap_ST_fsm_state31 = 56'd1073741824;
parameter    ap_ST_fsm_state32 = 56'd2147483648;
parameter    ap_ST_fsm_state33 = 56'd4294967296;
parameter    ap_ST_fsm_state34 = 56'd8589934592;
parameter    ap_ST_fsm_state35 = 56'd17179869184;
parameter    ap_ST_fsm_state36 = 56'd34359738368;
parameter    ap_ST_fsm_state37 = 56'd68719476736;
parameter    ap_ST_fsm_state38 = 56'd137438953472;
parameter    ap_ST_fsm_state39 = 56'd274877906944;
parameter    ap_ST_fsm_state40 = 56'd549755813888;
parameter    ap_ST_fsm_state41 = 56'd1099511627776;
parameter    ap_ST_fsm_state42 = 56'd2199023255552;
parameter    ap_ST_fsm_state43 = 56'd4398046511104;
parameter    ap_ST_fsm_state44 = 56'd8796093022208;
parameter    ap_ST_fsm_state45 = 56'd17592186044416;
parameter    ap_ST_fsm_state46 = 56'd35184372088832;
parameter    ap_ST_fsm_state47 = 56'd70368744177664;
parameter    ap_ST_fsm_state48 = 56'd140737488355328;
parameter    ap_ST_fsm_state49 = 56'd281474976710656;
parameter    ap_ST_fsm_state50 = 56'd562949953421312;
parameter    ap_ST_fsm_state51 = 56'd1125899906842624;
parameter    ap_ST_fsm_state52 = 56'd2251799813685248;
parameter    ap_ST_fsm_state53 = 56'd4503599627370496;
parameter    ap_ST_fsm_state54 = 56'd9007199254740992;
parameter    ap_ST_fsm_state55 = 56'd18014398509481984;
parameter    ap_ST_fsm_state56 = 56'd36028797018963968;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [127:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [55:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] G_vec_I_3;
reg   [31:0] G_vec_I_1;
reg   [31:0] G_vec_I_2;
reg   [31:0] G_vec_V_0;
reg   [31:0] G_vec_V_1;
reg   [31:0] G_vec_V_2;
wire   [31:0] grp_fu_180_p2;
reg   [31:0] mul_reg_660;
wire    ap_CS_fsm_state48;
wire   [31:0] grp_fu_185_p2;
reg   [31:0] mul2_reg_665;
wire   [31:0] grp_fu_190_p2;
reg   [31:0] mul1_reg_670;
wire   [31:0] grp_fu_165_p2;
reg   [31:0] add_reg_675;
wire    ap_CS_fsm_state52;
wire   [31:0] grp_fu_170_p2;
reg   [31:0] add3_reg_680;
wire   [31:0] grp_fu_175_p2;
reg   [31:0] add2_reg_685;
wire   [63:0] grp_fu_195_p1;
reg   [63:0] x_assign_reg_690;
wire    ap_CS_fsm_state54;
wire   [63:0] grp_fu_199_p1;
reg   [63:0] x_assign_1_reg_695;
wire   [63:0] grp_fu_203_p1;
reg   [63:0] x_assign_2_reg_700;
wire   [63:0] grp_generic_rint_double_s_fu_138_ap_return;
reg   [63:0] dc_reg_705;
wire    ap_CS_fsm_state55;
wire   [63:0] grp_generic_rint_double_s_fu_147_ap_return;
reg   [63:0] dc_1_reg_710;
wire   [63:0] grp_generic_rint_double_s_fu_156_ap_return;
reg   [63:0] dc_2_reg_715;
reg    grp_sinGen_fu_88_ap_start;
wire    grp_sinGen_fu_88_ap_done;
wire    grp_sinGen_fu_88_ap_idle;
wire    grp_sinGen_fu_88_ap_ready;
wire   [31:0] grp_sinGen_fu_88_G_vec_I_3;
wire    grp_sinGen_fu_88_G_vec_I_3_ap_vld;
wire   [31:0] grp_sinGen_fu_88_grp_fu_165_p_din0;
wire   [31:0] grp_sinGen_fu_88_grp_fu_165_p_din1;
wire   [1:0] grp_sinGen_fu_88_grp_fu_165_p_opcode;
wire   [31:0] grp_sinGen_fu_88_grp_fu_165_p_dout0;
wire    grp_sinGen_fu_88_grp_fu_165_p_ce;
wire   [31:0] grp_sinGen_fu_88_grp_fu_195_p_din0;
wire   [63:0] grp_sinGen_fu_88_grp_fu_195_p_dout0;
wire    grp_sinGen_fu_88_grp_fu_195_p_ce;
wire    grp_vetmat_fu_108_ap_start;
wire    grp_vetmat_fu_108_ap_done;
wire    grp_vetmat_fu_108_ap_idle;
wire    grp_vetmat_fu_108_ap_ready;
wire   [31:0] grp_vetmat_fu_108_G_vec_I_1_o;
wire    grp_vetmat_fu_108_G_vec_I_1_o_ap_vld;
wire   [31:0] grp_vetmat_fu_108_G_vec_I_2_o;
wire    grp_vetmat_fu_108_G_vec_I_2_o_ap_vld;
wire   [31:0] grp_vetmat_fu_108_G_vec_I_3_o;
wire    grp_vetmat_fu_108_G_vec_I_3_o_ap_vld;
wire   [31:0] grp_vetmat_fu_108_G_vec_V_0;
wire    grp_vetmat_fu_108_G_vec_V_0_ap_vld;
wire   [31:0] grp_vetmat_fu_108_G_vec_V_1;
wire    grp_vetmat_fu_108_G_vec_V_1_ap_vld;
wire   [31:0] grp_vetmat_fu_108_G_vec_V_2;
wire    grp_vetmat_fu_108_G_vec_V_2_ap_vld;
wire   [31:0] grp_vetmat_fu_108_grp_fu_165_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_165_p_din1;
wire   [1:0] grp_vetmat_fu_108_grp_fu_165_p_opcode;
wire   [31:0] grp_vetmat_fu_108_grp_fu_165_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_165_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_170_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_170_p_din1;
wire   [1:0] grp_vetmat_fu_108_grp_fu_170_p_opcode;
wire   [31:0] grp_vetmat_fu_108_grp_fu_170_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_170_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_175_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_175_p_din1;
wire   [1:0] grp_vetmat_fu_108_grp_fu_175_p_opcode;
wire   [31:0] grp_vetmat_fu_108_grp_fu_175_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_175_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_720_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_720_p_din1;
wire   [1:0] grp_vetmat_fu_108_grp_fu_720_p_opcode;
wire   [31:0] grp_vetmat_fu_108_grp_fu_720_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_720_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_724_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_724_p_din1;
wire   [1:0] grp_vetmat_fu_108_grp_fu_724_p_opcode;
wire   [31:0] grp_vetmat_fu_108_grp_fu_724_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_724_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_728_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_728_p_din1;
wire   [1:0] grp_vetmat_fu_108_grp_fu_728_p_opcode;
wire   [31:0] grp_vetmat_fu_108_grp_fu_728_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_728_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_732_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_732_p_din1;
wire   [1:0] grp_vetmat_fu_108_grp_fu_732_p_opcode;
wire   [31:0] grp_vetmat_fu_108_grp_fu_732_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_732_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_736_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_736_p_din1;
wire   [1:0] grp_vetmat_fu_108_grp_fu_736_p_opcode;
wire   [31:0] grp_vetmat_fu_108_grp_fu_736_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_736_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_740_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_740_p_din1;
wire   [1:0] grp_vetmat_fu_108_grp_fu_740_p_opcode;
wire   [31:0] grp_vetmat_fu_108_grp_fu_740_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_740_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_180_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_180_p_din1;
wire   [31:0] grp_vetmat_fu_108_grp_fu_180_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_180_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_185_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_185_p_din1;
wire   [31:0] grp_vetmat_fu_108_grp_fu_185_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_185_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_190_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_190_p_din1;
wire   [31:0] grp_vetmat_fu_108_grp_fu_190_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_190_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_744_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_744_p_din1;
wire   [31:0] grp_vetmat_fu_108_grp_fu_744_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_744_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_748_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_748_p_din1;
wire   [31:0] grp_vetmat_fu_108_grp_fu_748_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_748_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_752_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_752_p_din1;
wire   [31:0] grp_vetmat_fu_108_grp_fu_752_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_752_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_756_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_756_p_din1;
wire   [31:0] grp_vetmat_fu_108_grp_fu_756_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_756_p_ce;
wire   [31:0] grp_vetmat_fu_108_grp_fu_760_p_din0;
wire   [31:0] grp_vetmat_fu_108_grp_fu_760_p_din1;
wire   [31:0] grp_vetmat_fu_108_grp_fu_760_p_dout0;
wire    grp_vetmat_fu_108_grp_fu_760_p_ce;
wire    grp_histvect_fu_124_ap_start;
wire    grp_histvect_fu_124_ap_done;
wire    grp_histvect_fu_124_ap_idle;
wire    grp_histvect_fu_124_ap_ready;
wire   [31:0] grp_histvect_fu_124_G_vec_I_2_o;
wire    grp_histvect_fu_124_G_vec_I_2_o_ap_vld;
wire   [31:0] grp_histvect_fu_124_G_vec_I_1_o;
wire    grp_histvect_fu_124_G_vec_I_1_o_ap_vld;
wire   [31:0] grp_histvect_fu_124_grp_fu_720_p_din0;
wire   [31:0] grp_histvect_fu_124_grp_fu_720_p_din1;
wire   [1:0] grp_histvect_fu_124_grp_fu_720_p_opcode;
wire   [31:0] grp_histvect_fu_124_grp_fu_720_p_dout0;
wire    grp_histvect_fu_124_grp_fu_720_p_ce;
wire   [31:0] grp_histvect_fu_124_grp_fu_724_p_din0;
wire   [31:0] grp_histvect_fu_124_grp_fu_724_p_din1;
wire   [1:0] grp_histvect_fu_124_grp_fu_724_p_opcode;
wire   [31:0] grp_histvect_fu_124_grp_fu_724_p_dout0;
wire    grp_histvect_fu_124_grp_fu_724_p_ce;
wire   [31:0] grp_histvect_fu_124_grp_fu_744_p_din0;
wire   [31:0] grp_histvect_fu_124_grp_fu_744_p_din1;
wire   [31:0] grp_histvect_fu_124_grp_fu_744_p_dout0;
wire    grp_histvect_fu_124_grp_fu_744_p_ce;
wire    grp_generic_rint_double_s_fu_138_ap_start;
wire    grp_generic_rint_double_s_fu_138_ap_done;
wire    grp_generic_rint_double_s_fu_138_ap_idle;
wire    grp_generic_rint_double_s_fu_138_ap_ready;
wire    grp_generic_rint_double_s_fu_147_ap_start;
wire    grp_generic_rint_double_s_fu_147_ap_done;
wire    grp_generic_rint_double_s_fu_147_ap_idle;
wire    grp_generic_rint_double_s_fu_147_ap_ready;
wire    grp_generic_rint_double_s_fu_156_ap_start;
wire    grp_generic_rint_double_s_fu_156_ap_done;
wire    grp_generic_rint_double_s_fu_156_ap_idle;
wire    grp_generic_rint_double_s_fu_156_ap_ready;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state26;
reg    grp_vetmat_fu_108_ap_start_reg;
reg   [55:0] ap_NS_fsm;
wire    ap_NS_fsm_state27;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state35;
wire    ap_CS_fsm_state41;
reg    grp_histvect_fu_124_ap_start_reg;
wire    ap_NS_fsm_state42;
wire    ap_CS_fsm_state42;
wire    ap_CS_fsm_state49;
wire    ap_CS_fsm_state53;
wire    ap_CS_fsm_state56;
reg    grp_generic_rint_double_s_fu_138_ap_start_reg;
reg    grp_generic_rint_double_s_fu_147_ap_start_reg;
reg    grp_generic_rint_double_s_fu_156_ap_start_reg;
wire    ap_CS_fsm_state46;
reg   [31:0] grp_fu_165_p0;
reg   [31:0] grp_fu_165_p1;
reg   [31:0] grp_fu_170_p0;
reg   [31:0] grp_fu_170_p1;
reg   [31:0] grp_fu_175_p0;
reg   [31:0] grp_fu_175_p1;
reg   [31:0] grp_fu_180_p0;
reg   [31:0] grp_fu_180_p1;
reg   [31:0] grp_fu_185_p0;
reg   [31:0] grp_fu_185_p1;
reg   [31:0] grp_fu_190_p0;
reg   [31:0] grp_fu_190_p1;
reg   [31:0] grp_fu_195_p0;
wire   [63:0] data_V_fu_222_p1;
wire   [51:0] tmp_29_fu_243_p1;
wire   [53:0] mantissa_fu_247_p4;
wire   [10:0] tmp_28_fu_233_p4;
wire   [11:0] zext_ln510_fu_261_p1;
wire   [11:0] add_ln510_fu_265_p2;
wire   [10:0] sub_ln1311_fu_279_p2;
wire   [0:0] isNeg_fu_271_p3;
wire  signed [11:0] sext_ln1311_fu_285_p1;
wire   [11:0] ush_fu_289_p3;
wire  signed [31:0] sh_prom_i_i_i_i_i_cast_cast_cast_fu_297_p1;
wire   [136:0] zext_ln15_fu_257_p1;
wire   [136:0] sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_301_p1;
wire   [136:0] r_V_fu_305_p2;
wire   [0:0] tmp_fu_317_p3;
wire   [136:0] r_V_15_fu_311_p2;
wire   [31:0] zext_ln662_fu_325_p1;
wire   [31:0] tmp_s_fu_329_p4;
wire   [31:0] val_fu_339_p3;
wire   [0:0] p_Result_s_fu_225_p3;
wire   [31:0] result_V_3_fu_347_p2;
wire   [63:0] data_V_1_fu_361_p1;
wire   [51:0] tmp_31_fu_382_p1;
wire   [53:0] mantissa_1_fu_386_p4;
wire   [10:0] tmp_30_fu_372_p4;
wire   [11:0] zext_ln510_1_fu_400_p1;
wire   [11:0] add_ln510_1_fu_404_p2;
wire   [10:0] sub_ln1311_1_fu_418_p2;
wire   [0:0] isNeg_1_fu_410_p3;
wire  signed [11:0] sext_ln1311_1_fu_424_p1;
wire   [11:0] ush_1_fu_428_p3;
wire  signed [31:0] sh_prom_i_i_i_i_i14_cast_cast_cast_fu_436_p1;
wire   [136:0] zext_ln15_1_fu_396_p1;
wire   [136:0] sh_prom_i_i_i_i_i14_cast_cast_cast_cast_fu_440_p1;
wire   [136:0] r_V_16_fu_444_p2;
wire   [0:0] tmp_21_fu_456_p3;
wire   [136:0] r_V_17_fu_450_p2;
wire   [31:0] zext_ln662_2_fu_464_p1;
wire   [31:0] tmp_2_fu_468_p4;
wire   [31:0] val_1_fu_478_p3;
wire   [63:0] data_V_2_fu_492_p1;
wire   [51:0] tmp_33_fu_513_p1;
wire   [53:0] mantissa_2_fu_517_p4;
wire   [10:0] tmp_32_fu_503_p4;
wire   [11:0] zext_ln510_2_fu_531_p1;
wire   [11:0] add_ln510_2_fu_535_p2;
wire   [10:0] sub_ln1311_2_fu_549_p2;
wire   [0:0] isNeg_2_fu_541_p3;
wire  signed [11:0] sext_ln1311_2_fu_555_p1;
wire   [11:0] ush_2_fu_559_p3;
wire  signed [31:0] sh_prom_i_i_i_i_i35_cast_cast_cast_fu_567_p1;
wire   [136:0] zext_ln15_2_fu_527_p1;
wire   [136:0] sh_prom_i_i_i_i_i35_cast_cast_cast_cast_fu_571_p1;
wire   [136:0] r_V_18_fu_575_p2;
wire   [0:0] tmp_27_fu_587_p3;
wire   [136:0] r_V_19_fu_581_p2;
wire   [31:0] zext_ln662_3_fu_595_p1;
wire   [31:0] tmp_4_fu_599_p4;
wire   [31:0] val_2_fu_609_p3;
wire   [0:0] p_Result_28_fu_364_p3;
wire   [31:0] result_V_4_fu_486_p2;
wire   [0:0] p_Result_29_fu_495_p3;
wire   [31:0] result_V_6_fu_617_p2;
wire   [31:0] select_ln59_1_fu_631_p3;
wire   [31:0] result_V_7_fu_353_p3;
wire   [31:0] select_ln59_fu_623_p3;
reg    grp_fu_165_ce;
reg    grp_fu_170_ce;
reg    grp_fu_175_ce;
reg    grp_fu_180_ce;
reg    grp_fu_185_ce;
reg    grp_fu_190_ce;
reg    grp_fu_195_ce;
wire   [31:0] grp_fu_720_p2;
reg   [31:0] grp_fu_720_p0;
reg   [31:0] grp_fu_720_p1;
reg   [1:0] grp_fu_720_opcode;
reg    grp_fu_720_ce;
wire   [31:0] grp_fu_724_p2;
reg   [31:0] grp_fu_724_p0;
reg   [31:0] grp_fu_724_p1;
reg    grp_fu_724_ce;
wire   [31:0] grp_fu_728_p2;
wire   [31:0] grp_fu_728_p0;
wire   [31:0] grp_fu_728_p1;
reg    grp_fu_728_ce;
wire   [31:0] grp_fu_732_p2;
wire   [31:0] grp_fu_732_p0;
wire   [31:0] grp_fu_732_p1;
reg    grp_fu_732_ce;
wire   [31:0] grp_fu_736_p2;
wire   [31:0] grp_fu_736_p0;
wire   [31:0] grp_fu_736_p1;
reg    grp_fu_736_ce;
wire   [31:0] grp_fu_740_p2;
wire   [31:0] grp_fu_740_p0;
wire   [31:0] grp_fu_740_p1;
reg    grp_fu_740_ce;
wire   [31:0] grp_fu_744_p2;
reg   [31:0] grp_fu_744_p0;
reg   [31:0] grp_fu_744_p1;
reg    grp_fu_744_ce;
wire   [31:0] grp_fu_748_p2;
wire   [31:0] grp_fu_748_p0;
wire   [31:0] grp_fu_748_p1;
reg    grp_fu_748_ce;
wire   [31:0] grp_fu_752_p2;
wire   [31:0] grp_fu_752_p0;
wire   [31:0] grp_fu_752_p1;
reg    grp_fu_752_ce;
wire   [31:0] grp_fu_756_p2;
wire   [31:0] grp_fu_756_p0;
wire   [31:0] grp_fu_756_p1;
reg    grp_fu_756_ce;
wire   [31:0] grp_fu_760_p2;
wire   [31:0] grp_fu_760_p0;
wire   [31:0] grp_fu_760_p1;
reg    grp_fu_760_ce;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state36;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state40;
wire    ap_CS_fsm_state43;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state45;
wire    ap_CS_fsm_state47;
wire    ap_CS_fsm_state50;
wire    ap_CS_fsm_state51;
reg    ap_block_state55_on_subcall_done;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 56'd1;
#0 G_vec_I_3 = 32'd0;
#0 G_vec_I_1 = 32'd0;
#0 G_vec_I_2 = 32'd0;
#0 G_vec_V_0 = 32'd0;
#0 G_vec_V_1 = 32'd0;
#0 G_vec_V_2 = 32'd0;
#0 grp_vetmat_fu_108_ap_start_reg = 1'b0;
#0 grp_histvect_fu_124_ap_start_reg = 1'b0;
#0 grp_generic_rint_double_s_fu_138_ap_start_reg = 1'b0;
#0 grp_generic_rint_double_s_fu_147_ap_start_reg = 1'b0;
#0 grp_generic_rint_double_s_fu_156_ap_start_reg = 1'b0;
end

nodalSolver_sinGen grp_sinGen_fu_88(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sinGen_fu_88_ap_start),
    .ap_done(grp_sinGen_fu_88_ap_done),
    .ap_idle(grp_sinGen_fu_88_ap_idle),
    .ap_ready(grp_sinGen_fu_88_ap_ready),
    .G_vec_I_3(grp_sinGen_fu_88_G_vec_I_3),
    .G_vec_I_3_ap_vld(grp_sinGen_fu_88_G_vec_I_3_ap_vld),
    .grp_fu_165_p_din0(grp_sinGen_fu_88_grp_fu_165_p_din0),
    .grp_fu_165_p_din1(grp_sinGen_fu_88_grp_fu_165_p_din1),
    .grp_fu_165_p_opcode(grp_sinGen_fu_88_grp_fu_165_p_opcode),
    .grp_fu_165_p_dout0(grp_sinGen_fu_88_grp_fu_165_p_dout0),
    .grp_fu_165_p_ce(grp_sinGen_fu_88_grp_fu_165_p_ce),
    .grp_fu_195_p_din0(grp_sinGen_fu_88_grp_fu_195_p_din0),
    .grp_fu_195_p_dout0(grp_sinGen_fu_88_grp_fu_195_p_dout0),
    .grp_fu_195_p_ce(grp_sinGen_fu_88_grp_fu_195_p_ce)
);

nodalSolver_vetmat grp_vetmat_fu_108(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_vetmat_fu_108_ap_start),
    .ap_done(grp_vetmat_fu_108_ap_done),
    .ap_idle(grp_vetmat_fu_108_ap_idle),
    .ap_ready(grp_vetmat_fu_108_ap_ready),
    .G_vec_I_1_i(G_vec_I_1),
    .G_vec_I_1_o(grp_vetmat_fu_108_G_vec_I_1_o),
    .G_vec_I_1_o_ap_vld(grp_vetmat_fu_108_G_vec_I_1_o_ap_vld),
    .G_vec_I_2_i(G_vec_I_2),
    .G_vec_I_2_o(grp_vetmat_fu_108_G_vec_I_2_o),
    .G_vec_I_2_o_ap_vld(grp_vetmat_fu_108_G_vec_I_2_o_ap_vld),
    .G_vec_I_3_i(G_vec_I_3),
    .G_vec_I_3_o(grp_vetmat_fu_108_G_vec_I_3_o),
    .G_vec_I_3_o_ap_vld(grp_vetmat_fu_108_G_vec_I_3_o_ap_vld),
    .G_vec_V_0(grp_vetmat_fu_108_G_vec_V_0),
    .G_vec_V_0_ap_vld(grp_vetmat_fu_108_G_vec_V_0_ap_vld),
    .G_vec_V_1(grp_vetmat_fu_108_G_vec_V_1),
    .G_vec_V_1_ap_vld(grp_vetmat_fu_108_G_vec_V_1_ap_vld),
    .G_vec_V_2(grp_vetmat_fu_108_G_vec_V_2),
    .G_vec_V_2_ap_vld(grp_vetmat_fu_108_G_vec_V_2_ap_vld),
    .grp_fu_165_p_din0(grp_vetmat_fu_108_grp_fu_165_p_din0),
    .grp_fu_165_p_din1(grp_vetmat_fu_108_grp_fu_165_p_din1),
    .grp_fu_165_p_opcode(grp_vetmat_fu_108_grp_fu_165_p_opcode),
    .grp_fu_165_p_dout0(grp_vetmat_fu_108_grp_fu_165_p_dout0),
    .grp_fu_165_p_ce(grp_vetmat_fu_108_grp_fu_165_p_ce),
    .grp_fu_170_p_din0(grp_vetmat_fu_108_grp_fu_170_p_din0),
    .grp_fu_170_p_din1(grp_vetmat_fu_108_grp_fu_170_p_din1),
    .grp_fu_170_p_opcode(grp_vetmat_fu_108_grp_fu_170_p_opcode),
    .grp_fu_170_p_dout0(grp_vetmat_fu_108_grp_fu_170_p_dout0),
    .grp_fu_170_p_ce(grp_vetmat_fu_108_grp_fu_170_p_ce),
    .grp_fu_175_p_din0(grp_vetmat_fu_108_grp_fu_175_p_din0),
    .grp_fu_175_p_din1(grp_vetmat_fu_108_grp_fu_175_p_din1),
    .grp_fu_175_p_opcode(grp_vetmat_fu_108_grp_fu_175_p_opcode),
    .grp_fu_175_p_dout0(grp_vetmat_fu_108_grp_fu_175_p_dout0),
    .grp_fu_175_p_ce(grp_vetmat_fu_108_grp_fu_175_p_ce),
    .grp_fu_720_p_din0(grp_vetmat_fu_108_grp_fu_720_p_din0),
    .grp_fu_720_p_din1(grp_vetmat_fu_108_grp_fu_720_p_din1),
    .grp_fu_720_p_opcode(grp_vetmat_fu_108_grp_fu_720_p_opcode),
    .grp_fu_720_p_dout0(grp_vetmat_fu_108_grp_fu_720_p_dout0),
    .grp_fu_720_p_ce(grp_vetmat_fu_108_grp_fu_720_p_ce),
    .grp_fu_724_p_din0(grp_vetmat_fu_108_grp_fu_724_p_din0),
    .grp_fu_724_p_din1(grp_vetmat_fu_108_grp_fu_724_p_din1),
    .grp_fu_724_p_opcode(grp_vetmat_fu_108_grp_fu_724_p_opcode),
    .grp_fu_724_p_dout0(grp_vetmat_fu_108_grp_fu_724_p_dout0),
    .grp_fu_724_p_ce(grp_vetmat_fu_108_grp_fu_724_p_ce),
    .grp_fu_728_p_din0(grp_vetmat_fu_108_grp_fu_728_p_din0),
    .grp_fu_728_p_din1(grp_vetmat_fu_108_grp_fu_728_p_din1),
    .grp_fu_728_p_opcode(grp_vetmat_fu_108_grp_fu_728_p_opcode),
    .grp_fu_728_p_dout0(grp_vetmat_fu_108_grp_fu_728_p_dout0),
    .grp_fu_728_p_ce(grp_vetmat_fu_108_grp_fu_728_p_ce),
    .grp_fu_732_p_din0(grp_vetmat_fu_108_grp_fu_732_p_din0),
    .grp_fu_732_p_din1(grp_vetmat_fu_108_grp_fu_732_p_din1),
    .grp_fu_732_p_opcode(grp_vetmat_fu_108_grp_fu_732_p_opcode),
    .grp_fu_732_p_dout0(grp_vetmat_fu_108_grp_fu_732_p_dout0),
    .grp_fu_732_p_ce(grp_vetmat_fu_108_grp_fu_732_p_ce),
    .grp_fu_736_p_din0(grp_vetmat_fu_108_grp_fu_736_p_din0),
    .grp_fu_736_p_din1(grp_vetmat_fu_108_grp_fu_736_p_din1),
    .grp_fu_736_p_opcode(grp_vetmat_fu_108_grp_fu_736_p_opcode),
    .grp_fu_736_p_dout0(grp_vetmat_fu_108_grp_fu_736_p_dout0),
    .grp_fu_736_p_ce(grp_vetmat_fu_108_grp_fu_736_p_ce),
    .grp_fu_740_p_din0(grp_vetmat_fu_108_grp_fu_740_p_din0),
    .grp_fu_740_p_din1(grp_vetmat_fu_108_grp_fu_740_p_din1),
    .grp_fu_740_p_opcode(grp_vetmat_fu_108_grp_fu_740_p_opcode),
    .grp_fu_740_p_dout0(grp_vetmat_fu_108_grp_fu_740_p_dout0),
    .grp_fu_740_p_ce(grp_vetmat_fu_108_grp_fu_740_p_ce),
    .grp_fu_180_p_din0(grp_vetmat_fu_108_grp_fu_180_p_din0),
    .grp_fu_180_p_din1(grp_vetmat_fu_108_grp_fu_180_p_din1),
    .grp_fu_180_p_dout0(grp_vetmat_fu_108_grp_fu_180_p_dout0),
    .grp_fu_180_p_ce(grp_vetmat_fu_108_grp_fu_180_p_ce),
    .grp_fu_185_p_din0(grp_vetmat_fu_108_grp_fu_185_p_din0),
    .grp_fu_185_p_din1(grp_vetmat_fu_108_grp_fu_185_p_din1),
    .grp_fu_185_p_dout0(grp_vetmat_fu_108_grp_fu_185_p_dout0),
    .grp_fu_185_p_ce(grp_vetmat_fu_108_grp_fu_185_p_ce),
    .grp_fu_190_p_din0(grp_vetmat_fu_108_grp_fu_190_p_din0),
    .grp_fu_190_p_din1(grp_vetmat_fu_108_grp_fu_190_p_din1),
    .grp_fu_190_p_dout0(grp_vetmat_fu_108_grp_fu_190_p_dout0),
    .grp_fu_190_p_ce(grp_vetmat_fu_108_grp_fu_190_p_ce),
    .grp_fu_744_p_din0(grp_vetmat_fu_108_grp_fu_744_p_din0),
    .grp_fu_744_p_din1(grp_vetmat_fu_108_grp_fu_744_p_din1),
    .grp_fu_744_p_dout0(grp_vetmat_fu_108_grp_fu_744_p_dout0),
    .grp_fu_744_p_ce(grp_vetmat_fu_108_grp_fu_744_p_ce),
    .grp_fu_748_p_din0(grp_vetmat_fu_108_grp_fu_748_p_din0),
    .grp_fu_748_p_din1(grp_vetmat_fu_108_grp_fu_748_p_din1),
    .grp_fu_748_p_dout0(grp_vetmat_fu_108_grp_fu_748_p_dout0),
    .grp_fu_748_p_ce(grp_vetmat_fu_108_grp_fu_748_p_ce),
    .grp_fu_752_p_din0(grp_vetmat_fu_108_grp_fu_752_p_din0),
    .grp_fu_752_p_din1(grp_vetmat_fu_108_grp_fu_752_p_din1),
    .grp_fu_752_p_dout0(grp_vetmat_fu_108_grp_fu_752_p_dout0),
    .grp_fu_752_p_ce(grp_vetmat_fu_108_grp_fu_752_p_ce),
    .grp_fu_756_p_din0(grp_vetmat_fu_108_grp_fu_756_p_din0),
    .grp_fu_756_p_din1(grp_vetmat_fu_108_grp_fu_756_p_din1),
    .grp_fu_756_p_dout0(grp_vetmat_fu_108_grp_fu_756_p_dout0),
    .grp_fu_756_p_ce(grp_vetmat_fu_108_grp_fu_756_p_ce),
    .grp_fu_760_p_din0(grp_vetmat_fu_108_grp_fu_760_p_din0),
    .grp_fu_760_p_din1(grp_vetmat_fu_108_grp_fu_760_p_din1),
    .grp_fu_760_p_dout0(grp_vetmat_fu_108_grp_fu_760_p_dout0),
    .grp_fu_760_p_ce(grp_vetmat_fu_108_grp_fu_760_p_ce)
);

nodalSolver_histvect grp_histvect_fu_124(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_histvect_fu_124_ap_start),
    .ap_done(grp_histvect_fu_124_ap_done),
    .ap_idle(grp_histvect_fu_124_ap_idle),
    .ap_ready(grp_histvect_fu_124_ap_ready),
    .G_vec_V_2(G_vec_V_2),
    .G_vec_V_1(G_vec_V_1),
    .G_vec_I_2_i(G_vec_I_2),
    .G_vec_I_2_o(grp_histvect_fu_124_G_vec_I_2_o),
    .G_vec_I_2_o_ap_vld(grp_histvect_fu_124_G_vec_I_2_o_ap_vld),
    .G_vec_I_1_i(G_vec_I_1),
    .G_vec_I_1_o(grp_histvect_fu_124_G_vec_I_1_o),
    .G_vec_I_1_o_ap_vld(grp_histvect_fu_124_G_vec_I_1_o_ap_vld),
    .grp_fu_720_p_din0(grp_histvect_fu_124_grp_fu_720_p_din0),
    .grp_fu_720_p_din1(grp_histvect_fu_124_grp_fu_720_p_din1),
    .grp_fu_720_p_opcode(grp_histvect_fu_124_grp_fu_720_p_opcode),
    .grp_fu_720_p_dout0(grp_histvect_fu_124_grp_fu_720_p_dout0),
    .grp_fu_720_p_ce(grp_histvect_fu_124_grp_fu_720_p_ce),
    .grp_fu_724_p_din0(grp_histvect_fu_124_grp_fu_724_p_din0),
    .grp_fu_724_p_din1(grp_histvect_fu_124_grp_fu_724_p_din1),
    .grp_fu_724_p_opcode(grp_histvect_fu_124_grp_fu_724_p_opcode),
    .grp_fu_724_p_dout0(grp_histvect_fu_124_grp_fu_724_p_dout0),
    .grp_fu_724_p_ce(grp_histvect_fu_124_grp_fu_724_p_ce),
    .grp_fu_744_p_din0(grp_histvect_fu_124_grp_fu_744_p_din0),
    .grp_fu_744_p_din1(grp_histvect_fu_124_grp_fu_744_p_din1),
    .grp_fu_744_p_dout0(grp_histvect_fu_124_grp_fu_744_p_dout0),
    .grp_fu_744_p_ce(grp_histvect_fu_124_grp_fu_744_p_ce)
);

nodalSolver_generic_rint_double_s grp_generic_rint_double_s_fu_138(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_generic_rint_double_s_fu_138_ap_start),
    .ap_done(grp_generic_rint_double_s_fu_138_ap_done),
    .ap_idle(grp_generic_rint_double_s_fu_138_ap_idle),
    .ap_ready(grp_generic_rint_double_s_fu_138_ap_ready),
    .x(x_assign_reg_690),
    .ap_return(grp_generic_rint_double_s_fu_138_ap_return)
);

nodalSolver_generic_rint_double_s grp_generic_rint_double_s_fu_147(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_generic_rint_double_s_fu_147_ap_start),
    .ap_done(grp_generic_rint_double_s_fu_147_ap_done),
    .ap_idle(grp_generic_rint_double_s_fu_147_ap_idle),
    .ap_ready(grp_generic_rint_double_s_fu_147_ap_ready),
    .x(x_assign_1_reg_695),
    .ap_return(grp_generic_rint_double_s_fu_147_ap_return)
);

nodalSolver_generic_rint_double_s grp_generic_rint_double_s_fu_156(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_generic_rint_double_s_fu_156_ap_start),
    .ap_done(grp_generic_rint_double_s_fu_156_ap_done),
    .ap_idle(grp_generic_rint_double_s_fu_156_ap_idle),
    .ap_ready(grp_generic_rint_double_s_fu_156_ap_ready),
    .x(x_assign_2_reg_700),
    .ap_return(grp_generic_rint_double_s_fu_156_ap_return)
);

nodalSolver_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U79(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_165_p0),
    .din1(grp_fu_165_p1),
    .ce(grp_fu_165_ce),
    .dout(grp_fu_165_p2)
);

nodalSolver_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U80(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_170_p0),
    .din1(grp_fu_170_p1),
    .ce(grp_fu_170_ce),
    .dout(grp_fu_170_p2)
);

nodalSolver_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U81(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_175_p0),
    .din1(grp_fu_175_p1),
    .ce(grp_fu_175_ce),
    .dout(grp_fu_175_p2)
);

nodalSolver_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U82(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_180_p0),
    .din1(grp_fu_180_p1),
    .ce(grp_fu_180_ce),
    .dout(grp_fu_180_p2)
);

nodalSolver_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U83(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_185_p0),
    .din1(grp_fu_185_p1),
    .ce(grp_fu_185_ce),
    .dout(grp_fu_185_p2)
);

nodalSolver_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U84(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_190_p0),
    .din1(grp_fu_190_p1),
    .ce(grp_fu_190_ce),
    .dout(grp_fu_190_p2)
);

nodalSolver_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U85(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_195_p0),
    .ce(grp_fu_195_ce),
    .dout(grp_fu_195_p1)
);

nodalSolver_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U86(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add3_reg_680),
    .ce(1'b1),
    .dout(grp_fu_199_p1)
);

nodalSolver_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U87(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add2_reg_685),
    .ce(1'b1),
    .dout(grp_fu_203_p1)
);

nodalSolver_faddfsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_4_full_dsp_1_U88(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_720_p0),
    .din1(grp_fu_720_p1),
    .opcode(grp_fu_720_opcode),
    .ce(grp_fu_720_ce),
    .dout(grp_fu_720_p2)
);

nodalSolver_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U89(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_724_p0),
    .din1(grp_fu_724_p1),
    .ce(grp_fu_724_ce),
    .dout(grp_fu_724_p2)
);

nodalSolver_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U90(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_728_p0),
    .din1(grp_fu_728_p1),
    .ce(grp_fu_728_ce),
    .dout(grp_fu_728_p2)
);

nodalSolver_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U91(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_732_p0),
    .din1(grp_fu_732_p1),
    .ce(grp_fu_732_ce),
    .dout(grp_fu_732_p2)
);

nodalSolver_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U92(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_736_p0),
    .din1(grp_fu_736_p1),
    .ce(grp_fu_736_ce),
    .dout(grp_fu_736_p2)
);

nodalSolver_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U93(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_740_p0),
    .din1(grp_fu_740_p1),
    .ce(grp_fu_740_ce),
    .dout(grp_fu_740_p2)
);

nodalSolver_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U94(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_744_p0),
    .din1(grp_fu_744_p1),
    .ce(grp_fu_744_ce),
    .dout(grp_fu_744_p2)
);

nodalSolver_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U95(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_748_p0),
    .din1(grp_fu_748_p1),
    .ce(grp_fu_748_ce),
    .dout(grp_fu_748_p2)
);

nodalSolver_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U96(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_752_p0),
    .din1(grp_fu_752_p1),
    .ce(grp_fu_752_ce),
    .dout(grp_fu_752_p2)
);

nodalSolver_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U97(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_756_p0),
    .din1(grp_fu_756_p1),
    .ce(grp_fu_756_ce),
    .dout(grp_fu_756_p2)
);

nodalSolver_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U98(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_760_p0),
    .din1(grp_fu_760_p1),
    .ce(grp_fu_760_ce),
    .dout(grp_fu_760_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_generic_rint_double_s_fu_138_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state54)) begin
            grp_generic_rint_double_s_fu_138_ap_start_reg <= 1'b1;
        end else if ((grp_generic_rint_double_s_fu_138_ap_ready == 1'b1)) begin
            grp_generic_rint_double_s_fu_138_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_generic_rint_double_s_fu_147_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state54)) begin
            grp_generic_rint_double_s_fu_147_ap_start_reg <= 1'b1;
        end else if ((grp_generic_rint_double_s_fu_147_ap_ready == 1'b1)) begin
            grp_generic_rint_double_s_fu_147_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_generic_rint_double_s_fu_156_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state54)) begin
            grp_generic_rint_double_s_fu_156_ap_start_reg <= 1'b1;
        end else if ((grp_generic_rint_double_s_fu_156_ap_ready == 1'b1)) begin
            grp_generic_rint_double_s_fu_156_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_histvect_fu_124_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state42) & (1'b1 == ap_CS_fsm_state41))) begin
            grp_histvect_fu_124_ap_start_reg <= 1'b1;
        end else if ((grp_histvect_fu_124_ap_ready == 1'b1)) begin
            grp_histvect_fu_124_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_vetmat_fu_108_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state27) & (1'b1 == ap_CS_fsm_state26))) begin
            grp_vetmat_fu_108_ap_start_reg <= 1'b1;
        end else if ((grp_vetmat_fu_108_ap_ready == 1'b1)) begin
            grp_vetmat_fu_108_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_histvect_fu_124_G_vec_I_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state56))) begin
        G_vec_I_1 <= grp_histvect_fu_124_G_vec_I_1_o;
    end else if (((1'b1 == ap_CS_fsm_state27) & (grp_vetmat_fu_108_G_vec_I_1_o_ap_vld == 1'b1))) begin
        G_vec_I_1 <= grp_vetmat_fu_108_G_vec_I_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_histvect_fu_124_G_vec_I_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state56))) begin
        G_vec_I_2 <= grp_histvect_fu_124_G_vec_I_2_o;
    end else if (((1'b1 == ap_CS_fsm_state31) & (grp_vetmat_fu_108_G_vec_I_2_o_ap_vld == 1'b1))) begin
        G_vec_I_2 <= grp_vetmat_fu_108_G_vec_I_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state35) & (grp_vetmat_fu_108_G_vec_I_3_o_ap_vld == 1'b1))) begin
        G_vec_I_3 <= grp_vetmat_fu_108_G_vec_I_3_o;
    end else if (((1'b1 == ap_CS_fsm_state26) & (grp_sinGen_fu_88_G_vec_I_3_ap_vld == 1'b1))) begin
        G_vec_I_3 <= grp_sinGen_fu_88_G_vec_I_3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state41) & (grp_vetmat_fu_108_G_vec_V_0_ap_vld == 1'b1))) begin
        G_vec_V_0 <= grp_vetmat_fu_108_G_vec_V_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state41) & (grp_vetmat_fu_108_G_vec_V_1_ap_vld == 1'b1))) begin
        G_vec_V_1 <= grp_vetmat_fu_108_G_vec_V_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state41) & (grp_vetmat_fu_108_G_vec_V_2_ap_vld == 1'b1))) begin
        G_vec_V_2 <= grp_vetmat_fu_108_G_vec_V_2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        add2_reg_685 <= grp_fu_175_p2;
        add3_reg_680 <= grp_fu_170_p2;
        add_reg_675 <= grp_fu_165_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        dc_1_reg_710 <= grp_generic_rint_double_s_fu_147_ap_return;
        dc_2_reg_715 <= grp_generic_rint_double_s_fu_156_ap_return;
        dc_reg_705 <= grp_generic_rint_double_s_fu_138_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        mul1_reg_670 <= grp_fu_190_p2;
        mul2_reg_665 <= grp_fu_185_p2;
        mul_reg_660 <= grp_fu_180_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        x_assign_1_reg_695 <= grp_fu_199_p1;
        x_assign_2_reg_700 <= grp_fu_203_p1;
        x_assign_reg_690 <= grp_fu_195_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_165_ce = grp_vetmat_fu_108_grp_fu_165_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_165_ce = grp_sinGen_fu_88_grp_fu_165_p_ce;
    end else begin
        grp_fu_165_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_165_p0 = grp_vetmat_fu_108_grp_fu_165_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_165_p0 = grp_sinGen_fu_88_grp_fu_165_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_165_p0 = mul_reg_660;
    end else begin
        grp_fu_165_p0 = mul_reg_660;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_165_p1 = grp_vetmat_fu_108_grp_fu_165_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_165_p1 = grp_sinGen_fu_88_grp_fu_165_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_165_p1 = 32'd1191182336;
    end else begin
        grp_fu_165_p1 = 32'd1191182336;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_170_ce = grp_vetmat_fu_108_grp_fu_170_p_ce;
    end else begin
        grp_fu_170_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_170_p0 = grp_vetmat_fu_108_grp_fu_170_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_170_p0 = mul2_reg_665;
    end else begin
        grp_fu_170_p0 = mul2_reg_665;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_170_p1 = grp_vetmat_fu_108_grp_fu_170_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_170_p1 = 32'd1191182336;
    end else begin
        grp_fu_170_p1 = 32'd1191182336;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_175_ce = grp_vetmat_fu_108_grp_fu_175_p_ce;
    end else begin
        grp_fu_175_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_175_p0 = grp_vetmat_fu_108_grp_fu_175_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_175_p0 = mul1_reg_670;
    end else begin
        grp_fu_175_p0 = mul1_reg_670;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_175_p1 = grp_vetmat_fu_108_grp_fu_175_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_175_p1 = 32'd1191182336;
    end else begin
        grp_fu_175_p1 = 32'd1191182336;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_180_ce = grp_vetmat_fu_108_grp_fu_180_p_ce;
    end else begin
        grp_fu_180_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_180_p0 = grp_vetmat_fu_108_grp_fu_180_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        grp_fu_180_p0 = G_vec_V_2;
    end else begin
        grp_fu_180_p0 = G_vec_V_2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_180_p1 = grp_vetmat_fu_108_grp_fu_180_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        grp_fu_180_p1 = 32'd1132462080;
    end else begin
        grp_fu_180_p1 = 32'd1132462080;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_185_ce = grp_vetmat_fu_108_grp_fu_185_p_ce;
    end else begin
        grp_fu_185_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_185_p0 = grp_vetmat_fu_108_grp_fu_185_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        grp_fu_185_p0 = G_vec_V_1;
    end else begin
        grp_fu_185_p0 = G_vec_V_1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_185_p1 = grp_vetmat_fu_108_grp_fu_185_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        grp_fu_185_p1 = 32'd1132462080;
    end else begin
        grp_fu_185_p1 = 32'd1132462080;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_190_ce = grp_vetmat_fu_108_grp_fu_190_p_ce;
    end else begin
        grp_fu_190_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_190_p0 = grp_vetmat_fu_108_grp_fu_190_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        grp_fu_190_p0 = G_vec_V_0;
    end else begin
        grp_fu_190_p0 = G_vec_V_0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_190_p1 = grp_vetmat_fu_108_grp_fu_190_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        grp_fu_190_p1 = 32'd1132462080;
    end else begin
        grp_fu_190_p1 = 32'd1132462080;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_195_ce = grp_sinGen_fu_88_grp_fu_195_p_ce;
    end else begin
        grp_fu_195_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_195_p0 = grp_sinGen_fu_88_grp_fu_195_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        grp_fu_195_p0 = add_reg_675;
    end else begin
        grp_fu_195_p0 = add_reg_675;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43))) begin
        grp_fu_720_ce = grp_histvect_fu_124_grp_fu_720_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_720_ce = grp_vetmat_fu_108_grp_fu_720_p_ce;
    end else begin
        grp_fu_720_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43))) begin
        grp_fu_720_opcode = grp_histvect_fu_124_grp_fu_720_p_opcode;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_720_opcode = grp_vetmat_fu_108_grp_fu_720_p_opcode;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43))) begin
        grp_fu_720_p0 = grp_histvect_fu_124_grp_fu_720_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_720_p0 = grp_vetmat_fu_108_grp_fu_720_p_din0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43))) begin
        grp_fu_720_p1 = grp_histvect_fu_124_grp_fu_720_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_720_p1 = grp_vetmat_fu_108_grp_fu_720_p_din1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43))) begin
        grp_fu_724_ce = grp_histvect_fu_124_grp_fu_724_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_724_ce = grp_vetmat_fu_108_grp_fu_724_p_ce;
    end else begin
        grp_fu_724_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43))) begin
        grp_fu_724_p0 = grp_histvect_fu_124_grp_fu_724_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_724_p0 = grp_vetmat_fu_108_grp_fu_724_p_din0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43))) begin
        grp_fu_724_p1 = grp_histvect_fu_124_grp_fu_724_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_724_p1 = grp_vetmat_fu_108_grp_fu_724_p_din1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_728_ce = grp_vetmat_fu_108_grp_fu_728_p_ce;
    end else begin
        grp_fu_728_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_732_ce = grp_vetmat_fu_108_grp_fu_732_p_ce;
    end else begin
        grp_fu_732_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_736_ce = grp_vetmat_fu_108_grp_fu_736_p_ce;
    end else begin
        grp_fu_736_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_740_ce = grp_vetmat_fu_108_grp_fu_740_p_ce;
    end else begin
        grp_fu_740_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43))) begin
        grp_fu_744_ce = grp_histvect_fu_124_grp_fu_744_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_744_ce = grp_vetmat_fu_108_grp_fu_744_p_ce;
    end else begin
        grp_fu_744_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43))) begin
        grp_fu_744_p0 = grp_histvect_fu_124_grp_fu_744_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_744_p0 = grp_vetmat_fu_108_grp_fu_744_p_din0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43))) begin
        grp_fu_744_p1 = grp_histvect_fu_124_grp_fu_744_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_744_p1 = grp_vetmat_fu_108_grp_fu_744_p_din1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_748_ce = grp_vetmat_fu_108_grp_fu_748_p_ce;
    end else begin
        grp_fu_748_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_752_ce = grp_vetmat_fu_108_grp_fu_752_p_ce;
    end else begin
        grp_fu_752_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_756_ce = grp_vetmat_fu_108_grp_fu_756_p_ce;
    end else begin
        grp_fu_756_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29))) begin
        grp_fu_760_ce = grp_vetmat_fu_108_grp_fu_760_p_ce;
    end else begin
        grp_fu_760_ce = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_sinGen_fu_88_ap_start = 1'b1;
    end else begin
        grp_sinGen_fu_88_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            if (((1'b1 == ap_CS_fsm_state55) & (1'b0 == ap_block_state55_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state55;
            end
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln510_1_fu_404_p2 = ($signed(zext_ln510_1_fu_400_p1) + $signed(12'd3073));

assign add_ln510_2_fu_535_p2 = ($signed(zext_ln510_2_fu_531_p1) + $signed(12'd3073));

assign add_ln510_fu_265_p2 = ($signed(zext_ln510_fu_261_p1) + $signed(12'd3073));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state27 = ap_NS_fsm[32'd26];

assign ap_NS_fsm_state42 = ap_NS_fsm[32'd41];

always @ (*) begin
    ap_block_state55_on_subcall_done = ((grp_generic_rint_double_s_fu_156_ap_done == 1'b0) | (grp_generic_rint_double_s_fu_147_ap_done == 1'b0) | (grp_generic_rint_double_s_fu_138_ap_done == 1'b0));
end

assign ap_return = {{{{select_ln59_1_fu_631_p3}, {result_V_7_fu_353_p3}}, {select_ln59_fu_623_p3}}, {result_V_7_fu_353_p3}};

assign data_V_1_fu_361_p1 = dc_1_reg_710;

assign data_V_2_fu_492_p1 = dc_2_reg_715;

assign data_V_fu_222_p1 = dc_reg_705;

assign grp_fu_728_p0 = grp_vetmat_fu_108_grp_fu_728_p_din0;

assign grp_fu_728_p1 = grp_vetmat_fu_108_grp_fu_728_p_din1;

assign grp_fu_732_p0 = grp_vetmat_fu_108_grp_fu_732_p_din0;

assign grp_fu_732_p1 = grp_vetmat_fu_108_grp_fu_732_p_din1;

assign grp_fu_736_p0 = grp_vetmat_fu_108_grp_fu_736_p_din0;

assign grp_fu_736_p1 = grp_vetmat_fu_108_grp_fu_736_p_din1;

assign grp_fu_740_p0 = grp_vetmat_fu_108_grp_fu_740_p_din0;

assign grp_fu_740_p1 = grp_vetmat_fu_108_grp_fu_740_p_din1;

assign grp_fu_748_p0 = grp_vetmat_fu_108_grp_fu_748_p_din0;

assign grp_fu_748_p1 = grp_vetmat_fu_108_grp_fu_748_p_din1;

assign grp_fu_752_p0 = grp_vetmat_fu_108_grp_fu_752_p_din0;

assign grp_fu_752_p1 = grp_vetmat_fu_108_grp_fu_752_p_din1;

assign grp_fu_756_p0 = grp_vetmat_fu_108_grp_fu_756_p_din0;

assign grp_fu_756_p1 = grp_vetmat_fu_108_grp_fu_756_p_din1;

assign grp_fu_760_p0 = grp_vetmat_fu_108_grp_fu_760_p_din0;

assign grp_fu_760_p1 = grp_vetmat_fu_108_grp_fu_760_p_din1;

assign grp_generic_rint_double_s_fu_138_ap_start = grp_generic_rint_double_s_fu_138_ap_start_reg;

assign grp_generic_rint_double_s_fu_147_ap_start = grp_generic_rint_double_s_fu_147_ap_start_reg;

assign grp_generic_rint_double_s_fu_156_ap_start = grp_generic_rint_double_s_fu_156_ap_start_reg;

assign grp_histvect_fu_124_ap_start = grp_histvect_fu_124_ap_start_reg;

assign grp_histvect_fu_124_grp_fu_720_p_dout0 = grp_fu_720_p2;

assign grp_histvect_fu_124_grp_fu_724_p_dout0 = grp_fu_724_p2;

assign grp_histvect_fu_124_grp_fu_744_p_dout0 = grp_fu_744_p2;

assign grp_sinGen_fu_88_grp_fu_165_p_dout0 = grp_fu_165_p2;

assign grp_sinGen_fu_88_grp_fu_195_p_dout0 = grp_fu_195_p1;

assign grp_vetmat_fu_108_ap_start = grp_vetmat_fu_108_ap_start_reg;

assign grp_vetmat_fu_108_grp_fu_165_p_dout0 = grp_fu_165_p2;

assign grp_vetmat_fu_108_grp_fu_170_p_dout0 = grp_fu_170_p2;

assign grp_vetmat_fu_108_grp_fu_175_p_dout0 = grp_fu_175_p2;

assign grp_vetmat_fu_108_grp_fu_180_p_dout0 = grp_fu_180_p2;

assign grp_vetmat_fu_108_grp_fu_185_p_dout0 = grp_fu_185_p2;

assign grp_vetmat_fu_108_grp_fu_190_p_dout0 = grp_fu_190_p2;

assign grp_vetmat_fu_108_grp_fu_720_p_dout0 = grp_fu_720_p2;

assign grp_vetmat_fu_108_grp_fu_724_p_dout0 = grp_fu_724_p2;

assign grp_vetmat_fu_108_grp_fu_728_p_dout0 = grp_fu_728_p2;

assign grp_vetmat_fu_108_grp_fu_732_p_dout0 = grp_fu_732_p2;

assign grp_vetmat_fu_108_grp_fu_736_p_dout0 = grp_fu_736_p2;

assign grp_vetmat_fu_108_grp_fu_740_p_dout0 = grp_fu_740_p2;

assign grp_vetmat_fu_108_grp_fu_744_p_dout0 = grp_fu_744_p2;

assign grp_vetmat_fu_108_grp_fu_748_p_dout0 = grp_fu_748_p2;

assign grp_vetmat_fu_108_grp_fu_752_p_dout0 = grp_fu_752_p2;

assign grp_vetmat_fu_108_grp_fu_756_p_dout0 = grp_fu_756_p2;

assign grp_vetmat_fu_108_grp_fu_760_p_dout0 = grp_fu_760_p2;

assign isNeg_1_fu_410_p3 = add_ln510_1_fu_404_p2[32'd11];

assign isNeg_2_fu_541_p3 = add_ln510_2_fu_535_p2[32'd11];

assign isNeg_fu_271_p3 = add_ln510_fu_265_p2[32'd11];

assign mantissa_1_fu_386_p4 = {{{{1'd1}, {tmp_31_fu_382_p1}}}, {1'd0}};

assign mantissa_2_fu_517_p4 = {{{{1'd1}, {tmp_33_fu_513_p1}}}, {1'd0}};

assign mantissa_fu_247_p4 = {{{{1'd1}, {tmp_29_fu_243_p1}}}, {1'd0}};

assign p_Result_28_fu_364_p3 = data_V_1_fu_361_p1[32'd63];

assign p_Result_29_fu_495_p3 = data_V_2_fu_492_p1[32'd63];

assign p_Result_s_fu_225_p3 = data_V_fu_222_p1[32'd63];

assign r_V_15_fu_311_p2 = zext_ln15_fu_257_p1 << sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_301_p1;

assign r_V_16_fu_444_p2 = zext_ln15_1_fu_396_p1 >> sh_prom_i_i_i_i_i14_cast_cast_cast_cast_fu_440_p1;

assign r_V_17_fu_450_p2 = zext_ln15_1_fu_396_p1 << sh_prom_i_i_i_i_i14_cast_cast_cast_cast_fu_440_p1;

assign r_V_18_fu_575_p2 = zext_ln15_2_fu_527_p1 >> sh_prom_i_i_i_i_i35_cast_cast_cast_cast_fu_571_p1;

assign r_V_19_fu_581_p2 = zext_ln15_2_fu_527_p1 << sh_prom_i_i_i_i_i35_cast_cast_cast_cast_fu_571_p1;

assign r_V_fu_305_p2 = zext_ln15_fu_257_p1 >> sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_301_p1;

assign result_V_3_fu_347_p2 = (32'd0 - val_fu_339_p3);

assign result_V_4_fu_486_p2 = (32'd0 - val_1_fu_478_p3);

assign result_V_6_fu_617_p2 = (32'd0 - val_2_fu_609_p3);

assign result_V_7_fu_353_p3 = ((p_Result_s_fu_225_p3[0:0] == 1'b1) ? result_V_3_fu_347_p2 : val_fu_339_p3);

assign select_ln59_1_fu_631_p3 = ((p_Result_29_fu_495_p3[0:0] == 1'b1) ? result_V_6_fu_617_p2 : val_2_fu_609_p3);

assign select_ln59_fu_623_p3 = ((p_Result_28_fu_364_p3[0:0] == 1'b1) ? result_V_4_fu_486_p2 : val_1_fu_478_p3);

assign sext_ln1311_1_fu_424_p1 = $signed(sub_ln1311_1_fu_418_p2);

assign sext_ln1311_2_fu_555_p1 = $signed(sub_ln1311_2_fu_549_p2);

assign sext_ln1311_fu_285_p1 = $signed(sub_ln1311_fu_279_p2);

assign sh_prom_i_i_i_i_i14_cast_cast_cast_cast_fu_440_p1 = $unsigned(sh_prom_i_i_i_i_i14_cast_cast_cast_fu_436_p1);

assign sh_prom_i_i_i_i_i14_cast_cast_cast_fu_436_p1 = $signed(ush_1_fu_428_p3);

assign sh_prom_i_i_i_i_i35_cast_cast_cast_cast_fu_571_p1 = $unsigned(sh_prom_i_i_i_i_i35_cast_cast_cast_fu_567_p1);

assign sh_prom_i_i_i_i_i35_cast_cast_cast_fu_567_p1 = $signed(ush_2_fu_559_p3);

assign sh_prom_i_i_i_i_i_cast_cast_cast_cast_fu_301_p1 = $unsigned(sh_prom_i_i_i_i_i_cast_cast_cast_fu_297_p1);

assign sh_prom_i_i_i_i_i_cast_cast_cast_fu_297_p1 = $signed(ush_fu_289_p3);

assign sub_ln1311_1_fu_418_p2 = (11'd1023 - tmp_30_fu_372_p4);

assign sub_ln1311_2_fu_549_p2 = (11'd1023 - tmp_32_fu_503_p4);

assign sub_ln1311_fu_279_p2 = (11'd1023 - tmp_28_fu_233_p4);

assign tmp_21_fu_456_p3 = r_V_16_fu_444_p2[32'd53];

assign tmp_27_fu_587_p3 = r_V_18_fu_575_p2[32'd53];

assign tmp_28_fu_233_p4 = {{data_V_fu_222_p1[62:52]}};

assign tmp_29_fu_243_p1 = data_V_fu_222_p1[51:0];

assign tmp_2_fu_468_p4 = {{r_V_17_fu_450_p2[84:53]}};

assign tmp_30_fu_372_p4 = {{data_V_1_fu_361_p1[62:52]}};

assign tmp_31_fu_382_p1 = data_V_1_fu_361_p1[51:0];

assign tmp_32_fu_503_p4 = {{data_V_2_fu_492_p1[62:52]}};

assign tmp_33_fu_513_p1 = data_V_2_fu_492_p1[51:0];

assign tmp_4_fu_599_p4 = {{r_V_19_fu_581_p2[84:53]}};

assign tmp_fu_317_p3 = r_V_fu_305_p2[32'd53];

assign tmp_s_fu_329_p4 = {{r_V_15_fu_311_p2[84:53]}};

assign ush_1_fu_428_p3 = ((isNeg_1_fu_410_p3[0:0] == 1'b1) ? sext_ln1311_1_fu_424_p1 : add_ln510_1_fu_404_p2);

assign ush_2_fu_559_p3 = ((isNeg_2_fu_541_p3[0:0] == 1'b1) ? sext_ln1311_2_fu_555_p1 : add_ln510_2_fu_535_p2);

assign ush_fu_289_p3 = ((isNeg_fu_271_p3[0:0] == 1'b1) ? sext_ln1311_fu_285_p1 : add_ln510_fu_265_p2);

assign val_1_fu_478_p3 = ((isNeg_1_fu_410_p3[0:0] == 1'b1) ? zext_ln662_2_fu_464_p1 : tmp_2_fu_468_p4);

assign val_2_fu_609_p3 = ((isNeg_2_fu_541_p3[0:0] == 1'b1) ? zext_ln662_3_fu_595_p1 : tmp_4_fu_599_p4);

assign val_fu_339_p3 = ((isNeg_fu_271_p3[0:0] == 1'b1) ? zext_ln662_fu_325_p1 : tmp_s_fu_329_p4);

assign zext_ln15_1_fu_396_p1 = mantissa_1_fu_386_p4;

assign zext_ln15_2_fu_527_p1 = mantissa_2_fu_517_p4;

assign zext_ln15_fu_257_p1 = mantissa_fu_247_p4;

assign zext_ln510_1_fu_400_p1 = tmp_30_fu_372_p4;

assign zext_ln510_2_fu_531_p1 = tmp_32_fu_503_p4;

assign zext_ln510_fu_261_p1 = tmp_28_fu_233_p4;

assign zext_ln662_2_fu_464_p1 = tmp_21_fu_456_p3;

assign zext_ln662_3_fu_595_p1 = tmp_27_fu_587_p3;

assign zext_ln662_fu_325_p1 = tmp_fu_317_p3;

endmodule //nodalSolver
